### ISSUE TITLE
16x16 symlinks missing. wrong (black) icon in browser's save dialog.

### ISSUE THREAD

**Issue by Jarshvor** [PapirusDevelopmentTeam/papirus-folders#43] opened 2024-04-22 17:56 UTC
After installing papirus-icon-theme and papirus-folders, at some point I noticed that the small icons were not showing up correctly in my browser's save-dialog (both in firefox and vivaldi). They were black and barely noticeable on the dark background. (Not sure why black).

I had set my folder variant to adwaita via papirus-folders:
`papirus-folders -C adwaita --theme Papirus`

I tried reverting back to the default to see if that fixed the issue:
`papirus-folders -D --theme Papirus`
It did not.

Upon inspecting the /usr/share/icons/Papirus directory, I discovered that in the `16x16` dir, `folder.svg` (was black) and was not symlinked to folder-adwaita.svg

Manually symlinking the `16x16 folder.svg` proved to fix my issue.

I perused the code and papirus-folders seems to intentionally _not_ symlink the 16x16 sizes.
Am I correct in concluding that this was the cause for my issue?
Or is skipping 16x16 indeed intentional, and there is some other stuff going on?

**Comment by SmartFinn** [comment] 2024-05-02 09:35
Duplicate of #36

**Closed by SmartFinn** 2024-05-02 09:35 UTC
Labels: duplicate
